- name: apt-get update
  shell: apt-get update
  become: yes
  become_user: root

- name: install apt-get packages
  action: apt pkg={{item}} state=latest install_recommends=true force=true
  with_items:
    - emacs
    - realpath
    - git
    - tree
    - htop
    - autoconf
    - build-essential
    - gcc
    - gfortran
    - graphviz
    - idle-python2.7
    - libgle3
    - libqt4-dbus
    - libqt4-network
    - libqt4-script
    - libqt4-test
    - libqt4-xml
    - libqtcore4
    - libqtgui4
    - libtool
    - pkg-config
    - python-setuptools
    - python-pip
    - python-dev
    - python-imaging
    - python-lxml
    - python-numpy
    - python-opengl
    - python-pip
    - python-pyrex
    - python-pyside.qtopengl
    - python-qt4
    - python-qt4-gl
    - python-scipy
    - python-zmq
    - qt4-designer
    - qt4-dev-tools
    - swig
    - libfreetype6-dev
    - libxft-dev
    - libmysqlclient-dev
    - supervisor
  become: yes
  become_user: root

- name: pip upgrade
  shell: pip install --upgrade pip
  become: yes
  become_user: root

- name: pip bottle
  pip:
    name: bottle
  become: yes
  become_user: root




