- hosts: appservers

  vars:
    pub_keys_jin: https://github.com/jinfwhuang.keys
    pub_keys_yash: https://github.com/yashspatel23.keys
    pub_keys_saureen: https://github.com/samonderous.keys

    local_conf_credentialed: /Users/jin/code/work/arb/conf_credentialed
    remote_home_dir: /home/ubuntu/arb

  tasks:
    # -------------------
    # init
    # -------------------
    - name: apt-get update
      shell: apt-get update
      become: yes
      become_user: root
      tags: init

    - name: install apt-get packages
      action: apt pkg={{item}} state=latest install_recommends=true force=true
      with_items:
        - emacs
        - realpath
        - git
        - tree
        - htop
        - autoconf
        - build-essential
        - gcc
        - gfortran
        - graphviz
        - idle-python2.7
        - libgle3
        - libqt4-dbus
        - libqt4-network
        - libqt4-script
        - libqt4-test
        - libqt4-xml
        - libqtcore4
        - libqtgui4
        - libtool
        - pkg-config
        - python-setuptools
        - python-pip
        - python-dev
        - python-imaging
        - python-lxml
        - python-numpy
        - python-opengl
        - python-pip
        - python-pyrex
        - python-pyside.qtopengl
        - python-qt4
        - python-qt4-gl
        - python-scipy
        - python-zmq
        - qt4-designer
        - qt4-dev-tools
        - swig
        - libfreetype6-dev
        - libxft-dev
        - libmysqlclient-dev
        - supervisor
      become: yes
      become_user: root
      tags: init

    - name: pip install cython
      shell: pip install Cython
      become: yes
      become_user: root
      tags: init

    - name: pip upgrade
      shell: pip install --upgrade pip
      become: yes
      become_user: root
      tags: init

    - name: jin's pub key
      authorized_key:
        user: ubuntu
        state: present
        key: "{{ pub_keys_jin }}"
      tags: init,keys

    - name: yash's pub key
      authorized_key:
        user: ubuntu
        state: present
        key: "{{ pub_keys_yash }}"
      tags: init,keys

    - name: saureen's pub key
      authorized_key:
        user: ubuntu
        state: present
        key: "{{ pub_keys_saureen }}"
      tags: init,keys

    # -------------------
    # deploy
    # -------------------
    - name: git
      git:
        repo: git@github.com:yashspatel23/arb.git
        dest: "{{ remote_home_dir }}"
        version: master
        accept_hostkey: true
      tags: deploy

    - name: deploy dirs
      file: path="{{ remote_home_dir }}/{{ item }}" state=directory
      with_items:
        - 'deploy'
        - 'logs'
        - 'pids'
      tags: deploy

#    - name: supervisord config
#      copy:
#        src: ./production/supervisord.conf
#        dest: /etc/supervisor/supervisord.conf
#        mode: 0666
#        force: yes
#        owner: ubuntu
#        group: ubuntu
#      become: yes
#      become_user: root
#      tags: deploy

    - name: credentialed_conf
      copy:
        src: "{{ local_conf_credentialed }}"
        dest: "{{ remote_home_dir }}"
        mode: 0666
        force: yes
        owner: ubuntu
        group: ubuntu
      become: yes
      become_user: ubuntu
      tags: deploy,fast

    - name: deploy files
      copy:
        src: ./production/
        dest: "{{ remote_home_dir }}/deploy"
        mode: 0666
        force: yes
        owner: ubuntu
        group: ubuntu
      tags: deploy,fast

    - name: pip
      pip:
        requirements="{{ remote_home_dir }}/requirements.txt"
      become: yes
      become_user: root
      tags: deploy

    - name: start supervisord
      shell: ". conf_credentialed/env_prod && bash deploy/super_stop.sh && bash deploy/super_start.sh"
      args:
        chdir: "{{ remote_home_dir }}"
      become: yes
      become_user: root
      tags: deploy,fast

#    - name: supervisor
#      service: name=supervisor state=running
#      become: yes
#      become_user: root
#      tags: deploy

## supervisor
#sudo apt-get install supervisor
#update-rc.d -f supervisor remove
#update-rc.d supervisor defaults
#
#    # restart apps
#    - supervisorctl:
#        name: all
#        state: restarted
#        config: /etc/supervisor/supervisord.conf
#        server_url: http://localhost:5000






