- hosts: scraps__001

  tasks:
    # ------------------------
    # ubuntu
    # ------------------------
    
    - name: Git Pull from git@github.com:jinfwhuang/scraps.git
      shell: cd /home/ubuntu/scraps && git pull
      become: yes
      become_user: ubuntu
    
    - name: copy scraps/credentialed_conf/
      copy:
        src: /Users/jin/Dropbox/git-jin/scraps/credentialed_conf
        dest: /home/ubuntu/scraps
        mode: 0666
        force: yes
        owner: ubuntu
        group: ubuntu
      become: yes
      become_user: ubuntu
    
    # ------------------------
    # root
    # ------------------------
    
    # supervisord restart scraps
    - name: Restart scraps
      shell: supervisorctl restart scraps
    
